# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cosmos Pham
header-img: img/home-bg.jpg
email: inbox@buu.vn
copyright_name: "Cosmos Pham"
description: > #
    cat /var/log/life.error
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cosmospham.github.io" # the base hostname & protocol for your site
twitter_username: buuvn
github_username:  cosmospham
facebook_username:  buu.vn
email_username:  inbox@buu.vn
featured_image:  /assets/img/featured.jpg
app_id:  1707934562753534
# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:
  [jekyll-sitemap, jekyll-paginate, jekyll-feed]
